services:
  - type: web
    name: vconnect
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        value: your-very-secret-key
      - key: DEBUG
        value: False
