# Generated by Django 5.0.6 on 2025-03-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
